
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 07 22:22:27 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Si = 10;
  public static final int Cambiar = 14;
  public static final int Parentesis_c = 19;
  public static final int AND = 6;
  public static final int Parentesis_ap = 18;
  public static final int Numero = 25;
  public static final int OR = 7;
  public static final int Mas = 16;
  public static final int NOT = 8;
  public static final int flot = 4;
  public static final int Imprimir = 12;
  public static final int ERROR = 26;
  public static final int Identificador = 24;
  public static final int car = 3;
  public static final int Llave_c = 21;
  public static final int Punto_c = 23;
  public static final int Funcion = 11;
  public static final int Main = 22;
  public static final int EOF = 0;
  public static final int Escribir = 13;
  public static final int CONCA = 9;
  public static final int error = 1;
  public static final int Menos = 17;
  public static final int Igual = 15;
  public static final int ent = 2;
  public static final int Llave_ap = 20;
  public static final int consta = 5;
}

